### ISSUE TITLE
GA4 的跨網域追蹤

### ISSUE THREAD

**Issue by cjzopen** [doggy8088/TampermonkeyUserscripts#1]
Hello,

_ga 這個 query 有辦法過濾掉嗎？（Is there a way to filter out the query of "_ga"?）

thank you

**Comment by doggy8088** [comment]
Can you give me more example about the `_ga` usage? Or you can give me some official docs about this query string. Thanks!

**Comment by doggy8088** [comment]
@cjzopen 我加上這個參數了，多謝告知！ 👍
