### ISSUE TITLE
English version and improvement

### ISSUE THREAD

**Issue by neoOpus** [doggy8088/TampermonkeyUserscripts#11]
Hi,

I am working on fixing some of the issues and making this support more languages, and I would like to ask you some questions, I am not a Dev myself but I always manage to do things by tinkering, still I want to get better and make this extension with your help and of ChatGPT of course into something that many people around the globe would use...

I have already fixed some of the issues myself but I still have a lot to understand and lear, so I would like if you kindly tell me if you can assist me in some way or another... when I am stuck.

---

Translated by Gemini:

嗨！我正在努力修復一些問題，讓這個功能支援更多語言。為了做得更好，我想請教你一些問題。雖然我不是開發人員，但我常常自己動手嘗試解決問題。希望藉由你的協助，以及當然還有 ChatGPT 的幫忙，能將這個擴充功能打造成全球各地的人都愛用的東西。

我自己已經修復了一些問題，不過仍有很多需要學習的地方。所以，如果我遇到卡關的時候，不知道你能不能幫幫我呢？

**Comment by doggy8088** [comment]
So what things you have been fixed?
