### ISSUE TITLE
ChatGPT: 語音輸入與語音合成功能 (支援中/英/日/韓語言) 腳本無效

### ISSUE THREAD

**Issue by skysumbra** [doggy8088/TampermonkeyUserscripts#12]
你好

使用環境是 win 10 + chrome ，無法在`https://chat.openai.com/` 3.5 一般的版本來使用鍵盤指定按鈕來啟用腳本的功能

另外請問是否可以接受影片的聲音?
謝謝

**Comment by doggy8088** [comment]
因為 ChatGPT 網站加入了較為嚴格的 CSP 政策，所以程式目前無法執行了，我要另外找時間重寫程式才有辦法執行。

**Comment by doggy8088** [comment]
我已經重寫了程式，把所有 JS 全部都 bundle 進來，現在已經可以用了！
