### ISSUE TITLE
中、英文網頁切換器：Alt+S 快捷鍵在 Mac 會失效

### ISSUE THREAD

**Issue by leeyt** [doggy8088/TampermonkeyUserscripts#13]
在 Mac 按下 Alt+S 組合鍵，`KeyboardEvent` 物件中的 `key` 屬性會變成 `"ß"`，所以跟 `"s"` 比對會變 `false`，不會成功觸發中英文網頁切換。建議改用 `ev.altKey && ev.code === "keyS"` 來辨識 Alt+S 組合鍵，如此才能適用於 Windows 和 macOS 平台。

```javascript
{
  altKey: true,
  code: "KeyS",
  composed: true,
  ctrlKey: false,
  key: "ß",
  keyCode: 83,
  metaKey: false,
  shiftKey: false,
  // 省略其他屬性
}
```

**Comment by doggy8088** [comment]
可以發 PR 來嗎？

**Comment by doggy8088** [comment]
@leeyt Thanks! 👍
