### ISSUE TITLE
無法使用問題

### ISSUE THREAD

**Issue by felimet** [doggy8088/TampermonkeyUserscripts#16]
已下載安裝完成，但無法使用．
目前OpenAI將網域改為https://chatgpt.com/
這是造成無法使用的原因嗎？

**Comment by doggy8088** [comment]
你下載安裝什麼？我的腳本有數十支，你裝了哪一支？

**Comment by felimet** [comment]
您好，忘記說明了。
下載gpt語音輸入腳本。

**Comment by doggy8088** [comment]
那一支腳本我已經沒有在維護了，畢竟使用瀏覽器內建的語音識別服務，品質不太好
