### ISSUE TITLE
chatGPT回答朗读

### ISSUE THREAD

**Issue by lnavader** [doggy8088/TampermonkeyUserscripts#2]
老哥，非常好用，但是如何朗读chatGpt的回答呢？ 我尝试使用querySelectorAll查询所有P标签，将内容合并以后用SpeechSynthesis的speak来语音朗读chatGpt文本内容,但是失败了，UP有更好的办法没有，是否可以实现一下

**Comment by doggy8088** [comment]
最新版已經加上此功能，請重新安裝！👍

**Comment by lnavader** [comment]
老哥，👍

**Comment by lnavader** [comment]
老哥，插件非常完美，有一点点小问题，就是朗读回答时，因为语音一直处于开启状态，文本域又识别了朗读的内容，其他没有任何问题了。

**Comment by doggy8088** [comment]
這個問題最新版解決了，請重新安裝
