### ISSUE TITLE
他很好用，但是语音朗读语速过快而且有些刺耳，请问有没有什么办法更换语音包和调整语速语调？

### ISSUE THREAD

**Issue by xiaoyanmiao** [doggy8088/TampermonkeyUserscripts#6]

**Comment by doggy8088** [comment]
這裡可以調整

https://github.com/doggy8088/TampermonkeyUserscripts/blob/3cdd6825249d3927dcfa2e8f9db7d5ed94a88c14/dev/ChatGPTVoiceInput/ChatGPTVoiceInput.user.src.js#L927-L932
